🔧 Refactored code to use encryption algorithm name from settings for consistency
fastapi/full-stack-fastapi-template pull request #1160
Opened 2024-04-08 06:22 UTC by sameeramin

2024-05-08 16:24 UTC, menkotoglou approved these changes
I like it!

2024-05-09 13:30 UTC, sameeramin commented
Thank you @menkotoglou, please let me know what else I need to do in order to get this PR merged.

2024-05-10 08:42 UTC, menkotoglou commented
@sameeramin unfortunately I cannot do anything about it, since I'm not a repo maintainer.

2024-05-19 19:53 UTC, tiangolo requested changes
Thank you for the interest!

I don't think the algorithm should be configurable in the settings, it shouldn't really be variable. Let's better keep it in `security.py`.

But I agree that the backend utils should use the same variable from `security.py`. :nerd_face: Could you please update that?

2024-05-19 19:53 UTC, tiangolo commented on backend/app/utils.py
> +        algorithm=settings.ALGORITHM,
This could be from `security.ALGORITHM`

2024-05-19 19:53 UTC, tiangolo commented on backend/app/utils.py
> +            token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM]
This could be from `security.ALGORITHM`

2024-05-20 06:49 UTC, sameeramin commented
> Thank you for the interest!
> 
> I don't think the algorithm should be configurable in the settings, it shouldn't really be variable. Let's better keep it in `security.py`.
> 
> But I agree that the backend utils should use the same variable from `security.py`. 🤓 Could you please update that?

Sure, I'll update that!

2024-08-13 10:53 UTC, sameeramin commented
Hello @tiangolo, I have incorporated your suggestions

2024-08-16 00:28 UTC, julioriffel approved these changes

2024-09-27 16:42 UTC, tiangolo approved these changes

2024-09-27 16:42 UTC, tiangolo commented
Great, thanks @sameeramin! :rocket: :cake:

2024-09-27 16:42 UTC, merged